# Generated by Django 5.2.8 on 2025-11-18 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('ratio', models.FloatField(verbose_name='Коэффициент сжатия')),
            ],
            options={
                'verbose_name': 'Алгоритм',
                'verbose_name_plural': 'Алгоритмы',
                'db_table': 'algorithms',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Compression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('data_type', models.CharField(blank=True, null=True)),
                ('volume_after', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Математик')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Сжатие',
                'verbose_name_plural': 'Сжатия',
                'db_table': 'compressions',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='AlgorithmCompression',
            fields=[
                ('pk', models.CompositePrimaryKey('algorithm_id', 'compression_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('volume', models.IntegerField(default=0)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.algorithm')),
                ('compression', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.compression')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'algorithm_compression',
                'ordering': ('pk',),
            },
        ),
    ]
